#!/usr/bin/env bash

target=$(find $HOME/.password-store/ -name "*.gpg" -printf "%P\n" | dmenu -i -p "Get identifier for:")
username=$(basename $target .gpg | sed 's/\\/\\\\/g; s/"/\\"/g')
password=$(pass show ${target%.gpg} | sed 's/\\/\\\\/g; s/"/\\"/g')
echo "fake-key '<Esc>'"       >> $QUTE_FIFO
echo "fake-key \"$username\"" >> $QUTE_FIFO
echo "fake-key '<Tab>'"       >> $QUTE_FIFO
echo "fake-key \"$password\"" >> $QUTE_FIFO
echo "fake-key \"$password\"" > ~/.test
