#!/usr/bin/env bash

target=$(find $HOME/.password-store/ -name "*.gpg" -printf "%P\n" | dmenu -i -p "Get identifier for:")
echo "fake-key '<Esc>'"                       >> $QUTE_FIFO
echo "fake-key '$(basename $target .gpg)'"    >> $QUTE_FIFO
echo "fake-key '<Tab>'"                       >> $QUTE_FIFO
echo "fake-key '$(pass show ${target%.gpg})'" >> $QUTE_FIFO
