#!/usr/bin/env bash

target=$(find "$HOME"/.password-store/ -name "*.gpg" -printf "%P\\n" | dmenu -i -p "Get identifier for:")
[[ -z "$target" ]] && exit
username=$(basename "$target" .gpg | sed 's/\\/\\\\/g; s/"/\\"/g')
password=$(pass show "${target%.gpg}" | sed 's/\\/\\\\/g; s/"/\\"/g')
{ echo "fake-key '<Esc>'"; 
    echo "fake-key \"$username\"";
    echo "fake-key '<Tab>'";
    echo "fake-key \"$password\""; } >> "$QUTE_FIFO"
