#!/bin/zsh

# Commands
alias c='clear'
alias ca='printf "\ec"'
alias cdd='cd ~/dotfiles'

# Shortcut to files
alias notes='vim ~/dotfiles/.notes'
alias el='nvim ~/dotfiles/ledger/perso.ledger'

# Programs
alias a='vifm . .'
alias ff='FreeFem++'
alias g='git'
alias l='ledger'
alias m='cd ~/.mutt/attachments && mutt && cd -'
alias e='nvim'
alias n='nvim'
alias ns='nvim -S Session.vim'
alias v='vim'
alias vs="vim -S Session.vim"

# Build
alias mc='make clean'
alias mca='make clean-all'

# Tmux
alias son="tmux set -g status on"
alias soff="tmux set -g status off"

unalias ag
