#! /bin/zsh

# Load zgen
source "$HOME/.zsh/zgen/zgen.zsh"

# Load plugins
if ! zgen saved; then

    echo "Creating a zgen save"

    # Load oh-my-zsh framework
    zgen oh-my-zsh

    # Oh-my-zsh plugins
    zgen oh-my-zsh plugins/git
    zgen oh-my-zsh plugins/vi-mode
    zgen oh-my-zsh plugins/archlinux
    zgen oh-my-zsh plugins/ubuntu
    zgen oh-my-zsh plugins/tmux
    zgen oh-my-zsh plugins/themes

    # zsh-users plugins
    zgen load zsh-users/zsh-completions src
    zgen load zsh-users/zsh-syntax-highlighting

    # Appearance
    # zgen oh-my-zsh themes/eastwood
    zgen load mafredri/zsh-async
    zgen load sindresorhus/pure

    # Navigation plugins
    zgen load uvaes/fzf-marks

    # Other plugins
    zgen load rupa/z
    zgen load djui/alias-tips
    zgen load tarruda/zsh-autosuggestions

    # Save all to init script
    zgen save
fi

# Plugins configuration

# Autosuggestion
{
    ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=6'
    bindkey '^y' autosuggest-accept
}

# Z
export _Z_EXCLUDE_DIRS=("$HOME/sshfs", "$HOME/nfs")
