		repodirs[alols/xcape]=$home/xcape
		repodirs[altercation/mutt-colors-solarized]=$home/github/mutt-colors-solarized
		repodirs[atweiden/fzf-extras]=$home/github/fzf-extras
		repodirs[icholy/ttygif]=$home/github/ttygif
		repodirs[junegunn/fzf]=$home/.fzf
		repodirs[junegunn/vim-plug]=$dir/vim/vim-plug
repodirs[seebi/dircolors-solarized]=$home/github/dircolors
		repodirs[tarjoilija/zgen]=$home/.zgen
		repodirs[tmux-plugins/tpm]=$home/.tmux/plugins/tpm
		repodirs[uvaes/fzf-marks]=$home/github/fzf-marks
		repodirs[uvaes/grm]=$home/github/grm s/^[^[].*\(\[.*\]\).*$/\1/g
