#!/bin/bash

if [ "$COLORSCHEME" = "light" ]; then
    theme=light
elif [ "$COLORSCHEME" = "dark" ]; then
    theme=dark
else 
    echo $COLORSCHEME
fi

echo "/home/urbain/github/mutt-colors-solarized/mutt-colors-solarized-"$theme"-16.muttrc"
