#!/bin/zsh

# Directories
alias cdd='cd ~/dotfiles'

# Commands
alias a='vifm . .'
alias c='clear'
alias ca='printf "\ec"'
alias g='git'
alias m='cd ~/.mutt/attachments && mutt'
alias mc='make clean'
alias mca='make clean-all'
alias n='nvim'
alias v='vim'
alias vims="vim -S Session.vim"
alias vimtex='vim -S Session.vim --servername SYNC'
alias youtube='mpsyt'
alias notes='vim ~/dotfiles/.notes'

# Tmux
alias son="tmux set -g status on"
alias soff="tmux set -g status off"
