#!/bin/zsh

# Commands
alias c='clear'
alias ca='printf "\ec"'
alias cdd='cd ~/dotfiles'
alias notes='vim ~/dotfiles/.notes'

# Programs
alias a='vifm . .'
alias ff='FreeFem++'
alias g='git'
alias l='ledger -f ~/dotfiles/.ledger/perso.ledger'
alias lj='vim ~/dotfiles/.ledger/perso.ledger'
alias m='cd ~/.mutt/attachments && mutt && cd -'
alias n='newsbeuter'
alias v='vim'
alias vims="vim -S Session.vim"
alias vimtex='vim -S Session.vim --servername SYNC'

# Build
alias mc='make clean'
alias mca='make clean-all'

# Tmux
alias son="tmux set -g status on"
alias soff="tmux set -g status off"
