#!/bin/zsh

# Commands
alias c='clear'
alias ca='printf "\ec"'
alias cdd='cd ~/dotfiles'
alias notes='vim ~/dotfiles/.notes'

# Programs
alias a='vifm . .'
alias e='nvim'
alias ff='FreeFem++'
alias g='git'
alias l='ledger'
alias el='nvim ~/dotfiles/ledger/perso.ledger'
alias m='cd ~/.mutt/attachments && mutt && cd -'
alias n='newsbeuter'
alias v='nvim'
alias vims="nvim -S Session.vim"

# Build
alias mc='make clean'
alias mca='make clean-all'

# Tmux
alias son="tmux set -g status on"
alias soff="tmux set -g status off"
