#!/bin/zsh

function colo {

    # Change colors for current session
    $HOME/bin/recolor < ~/.Xresources/$1

    # Load Xresources file for future sessions
    xrdb -I$HOME ~/.Xresources/$1

    # Change environment variable
    export COLORSCHEME=$1

    # Change default environment variable for future sessions
    sed -i --follow-symlinks "s/^export COLORSCHEME=.*$/export COLORSCHEME=$1/g" ~/.zsh/tmp
}
